/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class FlexiBookApplicationTest {
    @Test void appHasAGreeting() {
        FlexiBookApplication classUnderTest = new FlexiBookApplication();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
